package batistaReviver.studentApi.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a professor entity within the institution.
 *
 * <p>This class is a JPA entity mapped to the "professors" table. It encapsulates the personal,
 * contact, and academic information of a professor. The use of Lombok annotations
 * (@Getter, @Setter, @NoArgsConstructor, @AllArgsConstructor) automatically generates the
 * corresponding boilerplate code for getters, setters, and constructors, simplifying the class
 * definition.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "professors")
public class Professor {

  /**
   * The unique identifier for the professor. This is the primary key, and its value is
   * automatically generated by the database using an identity strategy.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** The full name of the professor. This field is mandatory and cannot be null. */
  @NotBlank(message = "Name is required")
  @Column(nullable = false)
  private String name;

  /**
   * The phone number of the professor. This field is mandatory and must be unique across all
   * professor records.
   */
  @NotBlank(message = "Phone is required")
  @Pattern(regexp = "^\\+?[0-9. ()-]{7,25}$", message = "Phone number is invalid")
  @Column(nullable = false, unique = true)
  private String phone;

  /** The email address of the professor. This field is mandatory and must be unique. */
  @NotBlank(message = "Email is required")
  @Email(message = "Email should be valid")
  @Column(nullable = false, unique = true)
  private String email;

  /**
   * The unique institutional identification number for the professor (e.g., employee ID). This
   * field must be unique.
   */
  @NotBlank(message = "Register ID is required")
  @Column(unique = true)
  private String register;

  /**
   * Constructs a new Professor with specified details, excluding the database-generated ID. This
   * constructor is useful for creating new professor instances before persisting them.
   *
   * @param name The full name of the professor.
   * @param phone The unique phone number of the professor.
   * @param email The unique email address of the professor.
   * @param register The unique institutional identification number.
   */
  public Professor(String name, String phone, String email, String register) {
    this.name = name;
    this.phone = phone;
    this.email = email;
    this.register = register;
  }
}
