package batistaReviver.studentApi.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a student enrolled in the institution.
 *
 * <p>This entity is mapped to the "students" table in the database. It contains personal and
 * contact information for a student, along with their unique registration number. It also tracks
 * the student's subscriptions to various classes.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "students")
public class Student {

  /** The unique identifier for the student. This value is auto-generated by the database. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** The full name of the student. This field cannot be null. */
  @NotBlank(message = "Name is required")
  @Column(nullable = false)
  private String name;

  /** The phone number of the student. This field must be unique and cannot be null. */
  @NotBlank(message = "Phone is required")
  @Pattern(regexp = "^\\+?[0-9. ()-]{7,25}$", message = "Phone number is invalid")
  @Column(nullable = false, unique = true)
  private String phone;

  /** The email address of the student. This field must be unique and cannot be null. */
  @NotBlank(message = "Email is required")
  @Email(message = "Email should be valid")
  @Column(nullable = false, unique = true)
  private String email;

  /** The unique registration number for the student. */
  @NotBlank(message = "Register number is required")
  @Column(nullable = false, unique = true)
  private String register;

  /**
   * Constructs a new Student instance without an ID. This is useful for creating new student
   * records before they are persisted.
   *
   * @param name The student's full name.
   * @param phone The student's phone number.
   * @param email The student's email address.
   * @param register The student's registration number.
   */
  public Student(String name, String phone, String email, String register) {
    this.name = name;
    this.phone = phone;
    this.email = email;
    this.register = register;
  }
}
