package batistaReviver.studentApi.model;

import batistaReviver.studentApi.util.Role;
import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a user entity within the application.
 * <p>
 * This entity maps to the "users" table in the database and holds
 * authentication and profile information for the application's users.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "user_app")
public class UserApp {

  /**
   * The unique identifier for the user.
   * Automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The full name of the user.
   * This field is mandatory.
   */
  @NotBlank(message = "Name is required")
  private String name;

  /** * The email address of the student.
   * <p>
   * This field serves as the unique username for authentication.
   * It must be a valid email format, unique across the system, and cannot be null.
   */
  @NotBlank(message = "Email is required")
  @Email(message = "Email should be valid")
  @Column(nullable = false, unique = true)
  private String email;

  /**
   * The password for the user account.
   * <p>
   * This field is mandatory and must be at least 8 characters long.
   * It is recommended to store this as an encrypted hash rather than plain text.
   */
  @NotBlank(message = "Password is required")
  @Size(min = 8, message = "Password must be at least 8 characters long")
  private String password;

  /**
   * The security role assigned to the user.
   * <p>
   * Determines access levels and permissions within the application.
   * Defaults to {@link Role#USER} if not specified.
   */
  @Enumerated(EnumType.STRING)
  private Role role = Role.USER;

  /**
   * Constructs a new UserApp with specific details.
   * <p>
   * This constructor is useful for creating a new user instance before
   * it is persisted to the database (where the ID is generated).
   *
   * @param name     The full name of the user.
   * @param email    The unique email address of the user.
   * @param password The user's password (should ideally be encoded).
   * @param role     The role assigned to the user.
   */
  public UserApp(String name, String email, String password, Role role) {
    this.name = name;
    this.email = email;
    this.password = password;
    this.role = role;
  }
}